version: '3.8'

services:
  cda-mysql:
    image: mysql:8.0
    container_name: cda-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cda_db
    volumes:
      - cda-mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - cda-network
    ports:
      - "3306:3306"

  cda-phpmyadmin:
    image: phpmyadmin
    container_name: cda-phpmyadmin
    depends_on:
      - cda-mysql
    environment:
      PMA_HOST: cda-mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    networks:
      - cda-network
    ports:
      - "8080:80"

  cda-web:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: cda-web
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/cda-php.ini
    environment:
      DB_HOST: cda-mysql
      DB_DATABASE: cda_db
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
    networks:
      - cda-network
    depends_on:
      - cda-mysql
    user: "1000:1000"
   
  cda-frontend:
   image: node:18-alpine
   container_name: cda-frontend
   working_dir: /app
   volumes:
     - ./frontend:/app
   command: sh -c "npm install && npm run build && npx serve -s build -l 3000"
   ports:
     - "3001:3000"
   networks:
     - cda-network

  cda-nginx:
    image: nginx:alpine
    container_name: cda-nginx
    volumes:
      - ./backend/public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - cda-network
    depends_on:
      - cda-web

volumes:
  cda-mysql-data:

networks:
  cda-network:
    driver: bridge
